2025-04-19 14:55:56,726 - INFO - Starting FastAPI application...
2025-04-19 14:56:01,360 - INFO - Starting FastAPI application...
2025-04-19 14:59:28,294 - INFO - Starting FastAPI application...
2025-04-19 15:00:49,578 - INFO - Starting FastAPI application...
2025-04-19 15:01:41,307 - INFO - Starting FastAPI application...
2025-04-19 15:01:43,983 - INFO - Starting FastAPI application...
2025-04-19 15:01:51,499 - INFO - Starting FastAPI application...
2025-04-19 15:07:54,136 - INFO - Starting FastAPI application...
2025-04-19 15:07:58,345 - INFO - Starting FastAPI application...
2025-04-19 15:09:41,140 - INFO - Starting FastAPI application...
2025-04-19 15:10:16,778 - INFO - Starting FastAPI application...
2025-04-19 15:12:59,828 - INFO - Starting FastAPI application...
2025-04-19 15:16:33,181 - INFO - Starting FastAPI application...
2025-04-19 15:16:36,905 - ERROR - Get user failed
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 32, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 48, in get_current_user
    return GetUser(**user)
  File "/home/rgukt123/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
2025-04-19 15:18:54,207 - INFO - Starting FastAPI application...
2025-04-19 15:18:56,713 - INFO - Starting FastAPI application...
2025-04-19 15:18:58,407 - ERROR - 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 32, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 48, in get_current_user
    return GetUser(**user)
  File "/home/rgukt123/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
2025-04-19 15:19:06,737 - ERROR - 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 32, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 48, in get_current_user
    return GetUser(**user)
  File "/home/rgukt123/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
2025-04-19 15:19:07,870 - ERROR - 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 32, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 48, in get_current_user
    return GetUser(**user)
  File "/home/rgukt123/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
2025-04-19 15:19:32,020 - INFO - Starting FastAPI application...
2025-04-19 15:19:34,229 - ERROR - 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 32, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 48, in get_current_user
    return GetUser(**user)
  File "/home/rgukt123/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
2025-04-19 15:26:51,598 - INFO - Starting FastAPI application...
2025-04-19 15:26:57,737 - INFO - Starting FastAPI application...
2025-04-19 15:27:01,390 - INFO - Starting FastAPI application...
2025-04-19 15:28:24,977 - ERROR - 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 32, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 49, in get_current_user
    return GetUser(**user)
  File "/home/rgukt123/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
2025-04-19 15:32:55,368 - INFO - Starting FastAPI application...
2025-04-19 15:33:05,455 - INFO - Starting FastAPI application...
2025-04-19 15:33:11,749 - ERROR - 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 32, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 50, in get_current_user
    return GetUser(**user)
  File "/home/rgukt123/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
2025-04-19 15:33:31,065 - INFO - Starting FastAPI application...
2025-04-19 15:33:34,245 - ERROR - 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 33, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 50, in get_current_user
    return GetUser(**user)
  File "/home/rgukt123/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GetUser
id
  Field required [type=missing, input_value={'sub': '680364934a8038e0...', 'username': 'string'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
2025-04-19 15:39:43,136 - INFO - Starting FastAPI application...
2025-04-19 15:50:50,426 - INFO - Starting FastAPI application...
2025-04-19 15:54:31,055 - INFO - Starting FastAPI application...
2025-04-19 15:55:18,096 - INFO - Starting FastAPI application...
2025-04-19 15:55:21,087 - INFO - Starting FastAPI application...
2025-04-19 16:06:21,057 - INFO - Starting FastAPI application...
2025-04-19 16:08:31,062 - INFO - Starting FastAPI application...
2025-04-19 16:09:26,094 - INFO - Starting FastAPI application...
2025-04-19 16:09:51,895 - INFO - Starting FastAPI application...
2025-04-19 16:10:50,040 - INFO - Starting FastAPI application...
2025-04-19 16:15:02,894 - INFO - Starting FastAPI application...
2025-04-19 16:15:19,071 - INFO - Starting FastAPI application...
2025-04-19 16:15:23,662 - INFO - Starting FastAPI application...
2025-04-19 16:15:35,527 - INFO - Starting FastAPI application...
2025-04-19 16:19:52,709 - INFO - Starting FastAPI application...
2025-04-19 16:19:58,102 - INFO - Starting FastAPI application...
2025-04-19 16:27:16,284 - INFO - Starting FastAPI application...
2025-04-19 18:38:07,805 - INFO - Starting FastAPI application...
2025-04-19 18:38:14,503 - INFO - Starting FastAPI application...
2025-04-19 18:43:10,750 - INFO - Starting FastAPI application...
2025-04-19 18:43:44,445 - INFO - Starting FastAPI application...
2025-04-19 18:43:46,241 - INFO - Starting FastAPI application...
2025-04-19 18:44:56,992 - INFO - Starting FastAPI application...
2025-04-19 18:45:13,895 - INFO - Starting FastAPI application...
2025-04-19 18:46:00,311 - INFO - Starting FastAPI application...
2025-04-19 18:46:20,577 - INFO - Starting FastAPI application...
2025-04-19 18:49:10,850 - INFO - Starting FastAPI application...
2025-04-19 18:49:17,045 - INFO - Starting FastAPI application...
2025-04-19 18:51:00,435 - INFO - Starting FastAPI application...
2025-04-19 18:52:51,813 - INFO - Starting FastAPI application...
2025-04-19 18:53:53,905 - INFO - Starting FastAPI application...
2025-04-19 18:58:53,912 - INFO - Starting FastAPI application...
2025-04-19 19:01:55,628 - INFO - Starting FastAPI application...
2025-04-19 19:02:04,731 - INFO - Starting FastAPI application...
2025-04-19 19:06:22,476 - INFO - Starting FastAPI application...
2025-04-19 19:07:25,524 - INFO - Starting FastAPI application...
2025-04-19 19:07:43,221 - INFO - Starting FastAPI application...
2025-04-19 19:08:39,206 - INFO - Starting FastAPI application...
2025-04-19 19:10:50,414 - INFO - Starting FastAPI application...
2025-04-19 19:11:01,861 - INFO - Starting FastAPI application...
2025-04-19 19:28:21,881 - INFO - Starting FastAPI application...
2025-04-19 19:28:36,040 - INFO - Starting FastAPI application...
2025-04-19 19:28:52,121 - INFO - Starting FastAPI application...
2025-04-19 19:28:53,433 - INFO - Starting FastAPI application...
2025-04-19 19:29:21,079 - INFO - Starting FastAPI application...
2025-04-19 19:30:20,847 - INFO - Starting FastAPI application...
2025-04-19 19:34:22,610 - INFO - Starting FastAPI application...
2025-04-19 19:34:39,160 - INFO - Starting FastAPI application...
2025-04-19 19:34:55,853 - INFO - Starting FastAPI application...
2025-04-19 19:35:33,033 - INFO - Starting FastAPI application...
2025-04-19 19:35:44,038 - INFO - Starting FastAPI application...
2025-04-19 20:55:18,331 - INFO - Starting FastAPI application...
2025-04-19 21:01:56,524 - INFO - Starting FastAPI application...
2025-04-19 21:06:19,877 - INFO - Starting FastAPI application...
2025-04-19 21:11:00,752 - INFO - Starting FastAPI application...
2025-04-19 21:13:00,262 - INFO - Starting FastAPI application...
2025-04-19 21:13:10,946 - INFO - Starting FastAPI application...
2025-04-19 21:13:45,840 - INFO - Starting FastAPI application...
2025-04-19 21:13:50,986 - INFO - Starting FastAPI application...
2025-04-19 21:14:34,698 - INFO - Starting FastAPI application...
2025-04-19 21:14:37,964 - INFO - Starting FastAPI application...
2025-04-19 21:14:39,319 - INFO - Starting FastAPI application...
2025-04-19 21:15:13,728 - INFO - Starting FastAPI application...
2025-04-19 21:15:15,279 - INFO - Starting FastAPI application...
2025-04-20 00:03:19,052 - INFO - Starting FastAPI application...
2025-04-20 07:43:03,349 - INFO - Starting FastAPI application...
2025-04-20 07:48:10,111 - INFO - Starting FastAPI application...
2025-04-20 07:50:41,775 - INFO - Starting FastAPI application...
2025-04-20 07:52:00,488 - INFO - Starting FastAPI application...
2025-04-20 07:58:43,041 - INFO - Starting FastAPI application...
2025-04-20 09:36:03,683 - INFO - Starting FastAPI application...
2025-04-20 09:51:18,272 - INFO - Starting FastAPI application...
2025-04-20 09:57:48,148 - INFO - Starting FastAPI application...
2025-04-20 10:27:08,710 - INFO - Starting FastAPI application...
2025-04-20 10:29:03,492 - INFO - Starting FastAPI application...
2025-04-20 10:30:17,544 - INFO - Starting FastAPI application...
2025-04-20 10:34:26,010 - INFO - Starting FastAPI application...
2025-04-20 10:34:37,580 - INFO - Starting FastAPI application...
2025-04-20 10:35:27,793 - INFO - Starting FastAPI application...
2025-04-20 10:35:45,953 - INFO - Starting FastAPI application...
2025-04-20 10:39:01,312 - INFO - Starting FastAPI application...
2025-04-20 10:39:40,505 - INFO - Starting FastAPI application...
2025-04-20 10:40:26,204 - INFO - Starting FastAPI application...
2025-04-20 10:41:30,033 - INFO - Starting FastAPI application...
2025-04-20 10:45:36,929 - INFO - Starting FastAPI application...
2025-04-23 23:26:00,773 - INFO - Starting FastAPI application...
2025-04-23 23:28:34,230 - ERROR - JWT decoding error: Invalid crypto padding
2025-04-23 23:28:34,231 - ERROR - 401: Invalid token
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 33, in get_user
    return await get_current_user(token)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 49, in get_current_user
    raise HTTPException(status_code=401, detail="Invalid token")
fastapi.exceptions.HTTPException: 401: Invalid token
2025-04-25 22:11:37,229 - INFO - Starting FastAPI application...
2025-04-25 23:04:21,541 - INFO - Starting FastAPI application...
2025-04-27 20:49:18,209 - INFO - Starting FastAPI application...
2025-04-27 20:56:45,090 - INFO - Starting FastAPI application...
2025-04-27 21:41:31,994 - INFO - Starting FastAPI application...
2025-04-27 21:43:33,745 - ERROR - Login failed
Traceback (most recent call last):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/routes.py", line 22, in login
    return await login_user(user)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/auth/services.py", line 32, in login_user
    db_user = await users.find_one({"email": user.email})
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/collection.py", line 1755, in find_one
    for result in cursor.limit(-1):
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1284, in __next__
    return self.next()
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1260, in next
    if len(self._data) or self._refresh():
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1208, in _refresh
    self._send_message(q)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/cursor.py", line 1102, in _send_message
    response = client._run_operation(
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1896, in _run_operation
    return self._retryable_read(
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2005, in _retryable_read
    return self._retry_internal(
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1972, in _retry_internal
    ).run()
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2709, in run
    return self._read() if self._is_read else self._write()
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2854, in _read
    self._server = self._get_server()
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2802, in _get_server
    return self._client._select_server(
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1778, in _select_server
    topology = self._get_topology()
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1716, in _get_topology
    self._resolve_srv()
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 903, in _resolve_srv
    res = uri_parser._parse_srv(
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/uri_parser.py", line 164, in _parse_srv
    dns_options = dns_resolver.get_options()
  File "/home/rgukt123/programs/python aiml/linguabot-backend/venv/lib/python3.10/site-packages/pymongo/synchronous/srv_resolver.py", line 109, in get_options
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: The resolution lifetime expired after 21.125 seconds: Server Do53:127.0.0.53@53 answered The DNS operation timed out.; Server Do53:127.0.0.53@53 answered The DNS operation timed out.; Server Do53:127.0.0.53@53 answered The DNS operation timed out.; Server Do53:127.0.0.53@53 answered The DNS operation timed out.; Server Do53:127.0.0.53@53 answered The DNS operation timed out.; Server Do53:127.0.0.53@53 answered The DNS operation timed out.; Server Do53:127.0.0.53@53 answered The DNS operation timed out.
2025-04-27 21:54:00,211 - INFO - Starting FastAPI application...
2025-08-22 10:43:39,418 - INFO - Starting FastAPI application...
2025-08-22 10:49:10,333 - INFO - Starting FastAPI application...
2025-08-22 18:28:22,937 - INFO - Starting FastAPI application...
2025-08-23 10:01:49,757 - INFO - Starting FastAPI application...
2025-08-23 14:14:49,877 - INFO - Starting FastAPI application...
2025-08-23 17:55:02,542 - INFO - Starting FastAPI application...
2025-08-23 18:02:56,071 - INFO - Starting FastAPI application...
2025-08-23 18:38:26,263 - INFO - Starting FastAPI application...
2025-08-23 21:25:21,941 - INFO - Starting FastAPI application...
2025-08-24 18:07:21,667 - INFO - Starting FastAPI application...
2025-08-24 18:25:40,788 - INFO - Starting FastAPI application...
2025-08-24 18:35:15,173 - INFO - Starting FastAPI application...
2025-08-24 18:36:27,693 - INFO - Starting FastAPI application...
2025-08-24 18:36:46,934 - INFO - Starting FastAPI application...
2025-08-24 18:37:31,630 - INFO - Starting FastAPI application...
